# Generated by Django 6.0.6 on 2026-06-24 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid1, help_text="Identifiant de l'auteur", primary_key=True, serialize=False, unique=True, verbose_name='Auteur')),
                ('name', models.TextField(help_text="Nom de l'auteur.e", max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'auteur.e',
                'verbose_name_plural': 'auteur.es',
                'ordering': ['name', 'author_id'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.UUIDField(default=uuid.uuid1, help_text="Identifiant de la maison d'édition", primary_key=True, serialize=False, unique=True, verbose_name="Maison d'édition")),
                ('name', models.TextField(help_text="Nom de la maison d'édition.e", max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Maison d'édition",
                'verbose_name_plural': "Maisons d'édition",
                'ordering': ['name', 'publisher_id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(help_text='Code ISBN du livre', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ISBN')),
                ('title', models.TextField(help_text='Titre du livre', max_length=100, unique=True, verbose_name='Titre')),
                ('serie_type', models.CharField(blank=True, choices=[('i', 'inconnu'), ('os', 'one-shot'), ('s', 'serie'), ('hs', 'hors-serie')], default='i', help_text='Serie ? One-shot ? Hors-série (/spin-off) ?', max_length=2)),
                ('year_pub', models.IntegerField(help_text='Année de publication', null=True, verbose_name='Année')),
                ('description', models.TextField(blank=True, help_text='Description ou résumé du livre', null=True, verbose_name='Description')),
                ('author_id', models.ForeignKey(help_text="Identifiant de l'auteur", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.author', verbose_name='Auteur')),
                ('publisher_id', models.ForeignKey(help_text="Identifiant de la maison d'édition", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.publisher', verbose_name="Maison d'édition")),
            ],
            options={
                'verbose_name': 'livre',
                'verbose_name_plural': 'livres',
                'ordering': ['title', '-year_pub'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unique pour ce livre', primary_key=True, serialize=False, unique=True)),
                ('tome_nb', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('i', 'Inconnu'), ('l', 'Lu'), ('c', 'En cours'), ('p', 'Pause'), ('n', 'Pile à Lire')], default='u', help_text='statut', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelf.book')),
            ],
            options={
                'ordering': ['book', 'tome_nb', 'status'],
            },
        ),
    ]
